spring:
  application:
    name: Cinema
  datasource:
    name: cinema
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:cinema
    driver-class-name: org.h2.Driver
  sql:
    init:
      data-locations:
        - classpath:data-dev.sql


server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:file:./DB/cinema
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      data-locations:
        - classpath:data-test.sql

server:
  port: 8090