spring:
  application:
    name: Customer
  datasource:
    name: ${DB_NAME:customers}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:Admin$00}
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:customers
    driver-class-name: org.h2.Driver
  sql:
    init:
      data-locations:
        - classpath:data-dev.sql


server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:file:./data/customers
    driver-class-name: org.h2.Driver
  sql:
    init:
      data-locations:
        - classpath:data-test.sql
      mode: always

server:
  port: 8090