spring.application.name=VideoGames
spring.datasource.name=videoGames
spring.datasource.generate-unique-name=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization: true
spring.profiles.active=dev